/*
===============================================================
 #CUSTOM JavaScript
- Please do not edit this file. This file is generated from admin area.
- Every changes here will be overwritten by theme
===============================================================*/
    /* theme_options_custom 
=========================*/
if ( document.querySelector('.woocommerce-review-link') ) {
    document.querySelector('.woocommerce-review-link').addEventListener('click', function(event){
        event.preventDefault();
        var reviewTab = document.querySelector('#tab-title-reviews');
        if ( !reviewTab.classList.contains('active') ) {
            jQuery(reviewTab).find('a').trigger('click')           
        } 
    })
}
